1week/Yoojkim/20231231/boj_12847.java

code: Yoojkim_20231231

---

1week/jmjgirl/20240103/boj_11729.java

🔎 재귀 사용
N이 4일때까지 그림을 그려보니 옮긴 횟수가 2^n - 1 이라는 걸 알수 있었다.
💡 이동 순서
1. n-1개의 원판을 기둥 1에서 2로 옮기기
2. n번 원판만 기둥 1에서 3으로 옮기기
3. n-1개의 원판을 기둥 2에서 3으로 옮기기

code: jmjgirl_20240103

---

1week/Lydia/20230102/boj_14267.java

- 누적합
- 직원 n 명의 상사 번호를 배열에 저장
- 상사가 받은 칭찬의 수치를 배열에 저장
- 직원 n명을 for문으로 돌리며 본인 기준 직속 상사의 칭찬에서 본인이 받은 칭찬 수치 더함 (시간복잡도 O(n))
- 시간복잡도 O(n)
- [백준 회사문화 1](https://www.acmicpc.net/problem/14267)

code: Lydia_20240102

---

1week/codexong/20240102/baekjoon_10422

code: condexong_20240102

---

1week/Lydia/20240101/boj_10422.java

- DP (2차원)
- '(' 괄호 문자열의 개수를 행으로, 총 괄호 문자열의 전체 길이를 열로 지정
- 행을 기준으로 for문을 돌려서 올바른 문자열이 될 수 있는 경우의 수를 연산
- 처음 재귀 + stack을 이용한 로직(`fail`)에서 시간초과가 나서 DP 로직으로 수정(`success`)
- [백준 괄호](https://www.acmicpc.net/problem/10422)

code: Lydia_20240101

---

1week/Lydia/20240104/boj_1461.java

- 그리디 알고리즘
- 정렬
- 양수 배열과 음수 배열을 만들어 각각 내림차순, 오름차순 정렬을 해준 뒤, 가지고 갈 수 있는 책 M개수 만큼 걸음을 카운트 해줌
- 마지막에 가장 최대 걸음 수 한번을 제외해줌
- [백준 도서관](https://www.acmicpc.net/problem/1461)

code: Lydia_20240104

---

1week/Lydia/20240103/boj_11729.java

- 재귀
(코드 주석 참고)
- 초기
- start : 장대 1, mid : 장대 2, end : 장대 3
- 원판 3개가 있을 경우 start -> end로 원판 3개를 이동시키기 위해서는
- 원판 1, 2를 start -> mid로 옮기고 `a`
- 원판 3을 start -> end로 옮기고 `b`
- 그 위에 원판 1, 2를 mid -> end로 옮기면 원판 3위에 원판 1, 2가 올려진다. `c`
- 위 내용 `a` ~ `c`를 재귀로 사용하면 그 이전 값인 1, 2 부터 돌기 때문에 해당 코드가 점화식을 통한 규칙성을 갖게 됨
- 문제를 간단하게 생각하기 위해 세 개의 장대에 원판 3개를 옮기는 것을 예시로 구함
- [백준 하노이 탑 이동 순서](https://www.acmicpc.net/problem/11729)

code : Lydia_20240103

---

jmjgirl1/20240104/boj_1461.java

🔎 Greedy 알고리즘
🤔 첫번째 코드는 **런타임 에러** ... 
int max = pnArr.get(0) > Math.abs(nnArr.get(0)) ? pnArr.get(0) : Math.abs(nnArr.get(0));
int footPrint = 0;
for(int i=0; i<pnArr.size(); i+=m) {
footPrint += pnArr.get(i) * 2;
}
for(int i=0; i<nnArr.size(); i+=m) {
footPrint += Math.abs(nnArr.get(i)) * 2;
}
footPrint -= max;
생각해보니 nnArr과 pnArr이 empty일 경우를 생각을 안했어서 생긴 에러 였다!
🧐 수정한 코드
if(pnArr.isEmpty()) footPrint += -1 * nnArr.get(0);
else if(nnArr.isEmpty()) footPrint +=  pnArr.get(0);
else {
footPrint += Math.max(pnArr.get(0), -1 * nnArr.get(0));
footPrint += 2 * Math.min(pnArr.get(0), -1 * nnArr.get(0));
}
empty일 경우를 생각해줬다!

code: jmjgirl_20240104

---

1week/jmjgirl/20240105/프로그래머스_[3차] 방금그곡.java

💡 **해결 방법**
1. 음에 #이 붙은것들은 replaceAll()을 사용해서 다른 단어로 치환했다.
2. 악보는 repeat()과 substring()을 사용하여 음악 재생 시간만큼 만들어줬다.
</br>
🤔 **why**
if(m.length() > minutes) break;
찾아보니 이부분 때문에 테스트가 실패한거 같은데 만약 m이 "ABCDEFG"이고  minutes가 4이면 m은 당연히 악보에 포함될 수 없으니까 맞게 실행되는게 아닌가?😅 이부분은 지우고 실행하니 테스트가 통과됐다.

code: jmjgirl_20240105

---

1week/jmjgirl/20240107/boj_9084.java

💡 **다이나믹 프로그래밍** 사용
</br>
🔎 푼 방식
각 금액이 2와 3이고 만들어야할 금액이 10일때
1️⃣ **금액이 2일때** 10을 만들 수 있는 방법
- **dp[0]은 1로 무조건 고정**
| dp[0] | dp[1] | dp[2] | dp[3] | dp[4] | dp[5] | dp[6] | dp[7] | dp[8] | dp[9] | dp[10] |
|:--------:| :--------: |:--------:| :--------: |:--------:| :--------: |:--------:| :--------: |:--------:| :--------: |:--------:| 
| 1 | 0 | 1 | 0 | 1 | 0 | 1 | 0 | 1 | 0 | 1 |
<br>
2️⃣ **금액이 3일때** 10을 만들 수 있는 방법
- **dp[0]은 1로 무조건 고정**
| dp[0] | dp[1] | dp[2] | dp[3] | dp[4] | dp[5] | dp[6] | dp[7] | dp[8] | dp[9] | dp[10] |
|:--------:| :--------: |:--------:| :--------: |:--------:| :--------: |:--------:| :--------: |:--------:| :--------: |:--------:| 
| 1 | 0 | 1 | 1 | 1 | 1 | 2 | 1 | 2 | 2 | 2 |
dp[10] += dp[10 - 3] 이니까 1 + 1로 2다.

code : jmjgirl_20240107

---

1week/wjunheo/20240102/boj_14267.java
1week/wjunheo/20240105/프로그래머스_[3차] 방금그곡.java
1week/wjunheo/20240106/프로그래머스_이모티콘 할인행사.java

DFS
1.직원 수, 칭찬 횟수, 상하 관계를 입력할 배열과 리스트 생성
2. 상하 관계 리스트 초기화 및 설정.
3. 칭찬을 배열에 입력.
4. DFS사용하여 누적된 칭찬 계산.
저장할 리스트와 배열을 생각하는 것과 사장을 고려한 관계 설정이 쉽지 않았다.

code: wjunheo_20240102

---

2week/Lydia/20240109/programmers_호텔대실.java

- 구현
- 문자열
- 정렬
- 호텔 입실 시간을 기준으로 오름차순 정렬 -> 입실 시간이 동일할 경우 퇴실 시간을 기준으로 오름차순 정렬을 해줌
- 하나의 방을 기준으로 퇴실시간 + 10분을 한 값과 그 이후 방들의 입실시간을 비교
- 위 조건이 충족되어 하나의 객실에 다음 손님이 이용할 수 있을 경우 퇴실 시간을 다음 손님 기준으로 변경해주는 것이 핵심 ✅
- [호텔 대실](https://school.programmers.co.kr/learn/courses/30/lessons/155651)

code : Lydia_20240109

---

2week/Lydia/20240108/programmers_도넛과막대그래프.java

- 구현
- 각 정점에 대해 들어오는 화살표 개수와 나가는 화살표 개수를 저장
- 생성한 정점, 막대 모양 그래프, 8자 모양 그래프의 규칙성을 찾음
- 도넛 모양 그래프 개수 = 생성한 정점에서 나가는 화살표 개수 - (막대 모양 그래프 개수 + 8자 모양 그래프 개수)
- **생성한 정점에서 나가는 화살표 개수 = 생성된 그래프의 개수를 의미**
- 단순 아이디어를 생각하는 게 핵심 ✅
- 처음에 무작정 생성한 정점만 구하고 dfs로 그래프를 찾는 방식으로 진행하니 코드가 너무 길어져서 다른 방식으로 고민해보니 훨씬 간단한 방법이 있었음 (너무 어려운 방식으로 풀고있다면 다시 고민해 보는 것도 좋을 듯!)
- [프로그래머스 도넛과 막대 그래프](https://school.programmers.co.kr/learn/courses/30/lessons/258711)

code : Lydia_20240108

---

2week/Lydia/20240111/programmers_괄호변환.java

- 구현
- 재귀
- 문제 조건에 나와있는 로직 그대로 구현
- 재귀 구현에서 실수만 하지 않으면 특별히 어렵지 않은 문제
- [프로그래머스 괄호 변환](https://school.programmers.co.kr/learn/courses/30/lessons/60058?language=java)

code : Lydia_20240111

---

2week/jmjgirl/20240109/프로그래머스_호텔 대실.java

**정렬**
1. 대실 시작 시간 기준으로 정렬한다.
2. checkIn 시간, checkOut 시간을 분으로 바꾼다.
3. 입실이 불가능하면 rooms(ArrayList)에 checkOut 시간 + 10분을 한 시간을 넣어준다.
4. 입실이 가능하면 rooms중 입실이 가능한 room에 현재 checkOut + 10분으로 바꿔준다.
📌 https://school.programmers.co.kr/learn/courses/30/lessons/155651

code: jmjgirl_20240109

---

2week/Lydia/20240112/programmers_주사위고르기.java
2week/Lydia/20240112/programmers_주사윈고르기.java

- 재귀
- 해시맵
- 조합을 통해 A와 B가 각각 뽑는 주사위의 종류를 지정
- A가 뽑을 수 있는 숫자의 경우의 수를 HashMap에 저장 (caculate_A)
- 예를 들어 2를 4번 뽑았다면 -> `key : 2, value : 4`로 저장
- B가 뽑을 수 있는 숫자의 경우의 수를 HashMap에 저장 (calculate_B)
- A와 B의 경우의 수를 통해 A가 승리하는 경우의 수를 구함 (caculate_AB)
- 예를 들어, A -> key : 4, value : 2 이고, B -> key : 2, value : 3라면 A가 승리할 경우의 수는 2 * 3 ✅
- A가 승리하는 경우의 수를 ArrayList(시간초과😇) 자료구조에서 HashMap을 이용하는 자료구조로 변경한 뒤 정답 처리 완료
- [프로그래머스 주사위 고르기](https://school.programmers.co.kr/learn/courses/30/lessons/258709?language=java)

code : Lydia_20240112

---

3week/Lydia/20240116/programmers_디펜스게임.java

- 우선순위큐
- 준호가 가지고 있는 병사의 수에서 적을 뺀다. 
- 뺀 적의 수를 대해 PriorityQueue에 저장한다.
- 만약, 준호가 가지고 있는 병사가 음수일 경우 PriorityQueue에서 제일 큰 값에 대해 디펜스를 적용한다.
- 준호가 가지고 있는 병사가 음수이고 더이상 남은 디펜스가 없을 경우 게임이 종료된다.
- [프로그래머스 디펜스 게임](https://school.programmers.co.kr/learn/courses/30/lessons/142085)

code : Lydia_20240116

---

2week/jmjgirl/20240110/boj_2110.java

**이분 탐색**
- 첫번째 집은 무조건 설치한다는 가정
- 설치할 수 있는 공유기 개수 < 공유기 개수 c -> 거리가 길기 때문에 high를 줄인다.
- 설치할 수 있는 공유기 개수 >= 공유기 개수 c -> 거리가 짧기 때문에 low를 늘린다.
- 설치할 수 있는 공유기 개수 == 공유기 개수가 되었을 때 while문을 끝내지 않고 설치할 수 있는 공유기 개수 < 공유기 개수일때 끝나기 때문에 1을 빼준다.
처음에 이분 탐색으로 푸는 방법을 알지 못해서 고민하다가 풀이를 보고 이해하려고 했다...!
📌 [공유기](https://www.acmicpc.net/problem/2110)

code: jmjgirl_20240110

---

3week/jmjgirl/20240115/프로그래머스_표 병합.java

- update할때 merge한 값들도 함께 update하도록 주의!
- visited 배열을 사용해서 병합한 셀들 표시
😥[실패] : 테스트2, 9~18, 20번이 계속 실패하는데 이유를 모르겠어요...
📌 [표 병합](https://school.programmers.co.kr/learn/courses/30/lessons/150366)

code: jmjgirl_20240115 [실패]

---

2week/wjunheo/20240109/프로그래머스 호텔 대실

스위핑인가요?
예약 시간대에 몇개의 객실이 필요한지 구해내야함.
1. 시간기록 용 HashMap생성
2. 맵에 저장
3. 시간대별 객실수를 위해 keySet().toArray()
4. 순환후 Math.max(answer, current) 로 큰 값 리턴
10분후를 구연해주는게 중요했다. 그냥 10분더해주려니 안되어서 
메소드추가.
https://school.programmers.co.kr/learn/courses/30/lessons/155651

Create 프로그래머스 호텔 대실

---

3week/Lydia/20240117/programmers_n+1카드게임.java

- 구현
- 우선순위큐
- 기본적으로 라운드마다 각각의 숫자를 PriorityQueue에 저장
- 라운드에서 나온 숫자를 visitedCards 배열에 true로 체크함
- `visitedCards` : 이전부터 현재 라운드까지 등장한 숫자인지 체크
- 라운드를 지나갈 수 있는지 체크 : `isPossibleNext`
- 라운드를 지나갈 수 있는 경우
- **coin 0개를 쓸 경우** 
- 내가 기본적으로 가지고 있는 카드에서 라운드를 지나갈 수 있음
- **coin 1 or 2개를 쓸 경우**
- 무조건 한개라도 뽑아야지 라운드를 지나갈 수 있음
- 하지만, 만약 coin이 없다면 break -> 라운드 종료 ✨
- 하나의 PriorityQueue와 ArrayList를 사용해서 구현
- `PriorityQueue` : 라운드마다 뽑은 카드 저장
- num : 뽑은 숫자
- useCoin : 해당 숫자로 n+1을 만들기 위해 들어가는 Coin 개수 (1 or 2)
- 둘 다 뽑을 경우 : 2
- 처음 카드 뭉치에서 하나 사용하고 나머지 카드 하나만 뽑을 경우 : 1    
- round : 해당 숫자가 어떤 라운드에서 뽑혔는지
- `ArrayList` : 처음 카드뭉치에서 (n+1)이 되는 두장의 카드
- size() : 처음 카드뭉치로만 넘어갈 수 있는 라운드의 개수 
[프로그래머스 n+1 카드게임](https://school.programmers.co.kr/learn/courses/30/lessons/258707)

code : Lydia_20240117

---

3week/Lydia/20240118/programmers_조이스틱.java

- 탐욕법
- 구현
- A를 기준으로 최적의 값을 갱신함
- A가 아닌 값의 인덱스를 통해 좌 -> 우 이동 하는 케이스와 우 -> 좌로 이동하는 케이스를 분리해서 최적의 값을 구함
- 예시 : AZABA
- 좌 -> 우 (A(인덱스 0) -> A(인덱스 len-1) -> B -> A -> A -> Z) = 5
- 우 -> 좌 (A(인덱스 0) -> Z (인덱스 1) -> A -> A -> B) = 4
- 지금까지 푼 문제 중에 개인적으로 제일 어려웠던 것 같아요...😢
- [프로그래머스 조이스틱](https://school.programmers.co.kr/learn/courses/30/lessons/42860)

code : Lydia_20240118

---

3week/jmjgirl/20240118/프로그래머스_조이스틱.java

💡 Greedy 탐욕법
🔎 상하조작
- 각 알파벳을 'Z'에서 내려온것과 'A'에서 올라간 것의 최솟값을 구해주면된다.
</br>
🔎 좌우조작 (이부분에서 막혔다😥)
- 최소 횟수를 구해야하는데 3가지 방법이 있다. name이 **BBZAAAC**라 하면
**1. 처음부터 쭉 오른쪽으로 가는 경우** = size - 1
**2. 오른쪽으로 갔다가 다시 리턴해서 왼쪽 가는 경우**
- BBZ까지 갔다가 다시 돌아가서 C로 가는 경우
- (i*2) + size - next;
**3. 왼쪽으로 갔다가 다시 리턴해서 오른쪽으로 가는 경우**
- C부터 간 후에 다시 돌아가서 BBZ로 가는 경우
- (size - next)*2 + i
📌 [조이스틱](https://school.programmers.co.kr/learn/courses/30/lessons/42860)

code: jmjgirl_20240118

---

4week/Lydia/20240124/boj_15683.java
4week/Lydia/20240124/boj_15683_refactor.java

- 구현
- 완전탐색
- DFS
- BFS
- DFS를 이용한 완전탐색으로 각각 회전에 따른 CCTV의 방향 배열을 설정
- CCTV의 방향을 설정한 뒤 그 경우마다 BFS를 이용해 사각지대의 최소 크기를 갱신
- `getNextDir` 함수를 개선하고 싶은데 고민중 -> `refactoring` 완료 ✨
- **boj_15683_refactor.java 코드** 참고
```java
public static int[] getNextDir(int cctvType, int direction) {
int[][] nextDir = {{}, {0}, {0, 2}, {0, 1}, {0, 1, 3}, {0, 1, 2, 3}};
for(int i=0; i<nextDir[cctvType].length; i++) {
nextDir[cctvType][i] = (nextDir[cctvType][i] + direction) % 4;
}
return nextDir[cctvType];
}
```
- [백준 감시](https://www.acmicpc.net/problem/15683)

code: Lydia_20240124

---

4week/Lydia/20240125/programmers_입국심사.java

- 이분탐색
- 모든 사람이 심사 받는데 걸리는 시간을 기준으로 이분탐색을 진행 (mid)
- 해당 시간에 몇명이나 심사를 받을 수 있는지 times 배열을 통해 계산해줌
- 계산한 값이 n보다 크거나 같을 경우 정답을 갱신
- 최대의 경우 한명의 심사관이 입국심사를 기다리는 모든 사람을 심사할 수도 있으므로 타입 범위주의 
- `max : 1000000000 * 1000000000`
- [프로그래머스 입국심사](https://school.programmers.co.kr/learn/courses/30/lessons/43238)

code : Lydia_20240125

---

4week/Lydia/20240127/programmers_다단계칫솔판매.java

- 구현
- DFS
- 판매원과 추천인을 기준으로 HashMap Parent Chaining을 함
- DFS를 이용하여 판매원이 판매를 할 경우 해당 금액에 10%를 계산한 금액을 추천인에게 적용
- 추천인에게 적용한 값을 제외하고 판매량을 갱신해주는 것이 포인트 ✨
- [프로그래머스 다단계 칫솔 판매](https://school.programmers.co.kr/learn/courses/30/lessons/77486)

code : Lydia_20240127

---

5week/Lydia/20240129/boj_1043.java

- DFS
- 그래프 탐색
- 같은 파티인 사람들끼리 양방향 그래프를 연결해줌
- 진실을 알고 있는 사람을 기준으로 DFS를 돌려 같은 파티에 간 사람도 진실을 알고 있다고 체크
- 파티를 대표하는 사람을 기준으로 진실을 알고 있는지 체크하여 진실을 모르는 파티만 answer 갱신
- 한명만 체크해도 어차피 해당 파티원은 모두 진실을 아는 것을 의미
- 쉬운 문제, 빠르게 푸는게 관건
- [백준 거짓말](https://www.acmicpc.net/problem/1043)

code : Lydia_20240129

---

5week/Lydia/20240201/boj_11660.java

- 누적합
- 행을 기준으로 누적합을 먼저 arr에 저장
- 구하고자 하는 x2와 x1의 차를 통해 두 사이 값들에 대한 합을 O(1) 시간복잡도로 계산
- 누적합 형식으로 arr에 값을 저장하는 것이 핵심
- [백준 구간 합 구하기 5](https://www.acmicpc.net/problem/11660)

code : Lydia_20240201

---

5week/Lydia/20240130/programmers_인사고과.java

- 구현
- 정렬
- 근무 태도 점수를 기준으로 내림차순 정렬을 한 뒤 동료 평가 점수를 기준으로 두 점수가 모두 낮은 경우가 있는지 체크
- 근무 태도 점수는 이미 더 낮기 때문에 동료 평가 점수만 비교해도 되서 시간 복잡도가 O(n)이 걸리도록 만드는 것이 핵심!
- 오히려 처음에 너무 어렵게 접근해서 문제를 고민하는 시간이 오래 걸림 😭
- [프로그래머스 인사고과](https://school.programmers.co.kr/learn/courses/30/lessons/152995)

code : Lydia_20240130

---

5week/Yoojkim/programmers_49189.java

- BFS
- 자료구조(큐)
간단한 BFS 문제이다. 
현재 큐에 들어가있는 노드와 하나의 간선으로만 연결된 노드를 큐에 다시 넣어주고, 이러한 노드들의 갯수를 매번 기록한다.
BFS가 끝나면 기록된 갯수 중 마지막에서 두번째를 반환한다. 
**마지막 기록은 0이기 때문이다. **
간단한 문제라 빨리 푸는 게 관건
https://school.programmers.co.kr/learn/courses/30/lessons/49189

[programmers_49189] 가장 먼 노드

---

6week/Yoojkim/programmers_133500

- DFS
- 자료구조 (tree)
DFS를 이용해서 풀 수 있는 문제였다. 
시작 노드를 1로 해서, 시작 노드부터 모든 노드까지 DFS를 통해 불을 킬 등대를 찾으면 된다.
DFS 메소드에서 현재 노드가 leaf인지 / root인지 여부를 따져야 한다.
- leaf 경우: 등대를 끄는 것이 무조건 최적이다.
- root 경우: 자식 노드들의 상태에 따라 등대 여부가 결정된다.
위에서 언급한 root의 경우,
자식 노드 중 하나라도 리프 노드인 경우 -> 현재 root 노드를 켜야 한다.
**추가적으로, 자식 노드가 이미 DFS를 한 노드라면 DFS를 수행하지 않는다.**
간단한 문제지만 나에겐 높은 난이도로 다가오는 문제였다.
그 이유는 트리 구조를 구현하는 것이 생소했고 이 와중에 DFS, DP 등 다양한 개념을 접목하려고 했기 때문이다.
또한 처음에 MST로 접근하려고 했던 것도 문제였다. (MST로 구현할 수 있는지는 잘 모르겠음)
관련된 문제를 많이 풀어봐야할 것 같다. 
https://school.programmers.co.kr/learn/courses/30/lessons/133500

[programmers_133500] 등대

---

5week/Yoojkim/boj_11660.java

- 누적합
2차원 배열을 입력 받으면서 동시에 (0,0)~(i,j)까지의 직사각형 누적합을 계산한다.
이후 필요한 구간의 값은 누적합 값을 통해 O(1)의 시간복잡도로 계산한다.
다른 분들의 코드를 본 후 다시 코드를 보니까 배열을 N+1로 설정한 장점을 이용하지 못했다.
1~N까지 배열이 존재하기 때문에 구간 검증을 하지 않아도 되고,
코드가 상당히 복잡하고 이해하기 어렵다. 보다 더 직관적으로 코드를 작성하는 것이 중요할 것 같다.
*하연님 행으로 누적합 구하는 코드도 후에 참고해서 리팩토링 하는 것이 좋을 거 같다.
https://www.acmicpc.net/problem/11660

[boj_11660] 구간 합 구하기 5

---

5week/Yoojkim/20240131/programmers_42861.java

- MST
MST를 구하면 되는 간단한 문제이다.
원래는 Kruskal로 풀었는데, 이 문제 같은 경우 Prim이라 Prim으로 구현하는 것이 좋을 것 같다. (코드는 Prim)
https://school.programmers.co.kr/learn/courses/30/lessons/42861

[programmers_42861] 섬 연결하기

---

4week/Yoojkim/20240123/programmers_214289
4week/Yoojkim/20240129/boj_1043.java

- DP
다이나믹 프로그래밍을 이용하여 풀 수 있는 문제였다.
완전탐색으로도 가능하지만(시간 복잡도가 낮음) 조건이 너무 많아 다이나믹 프로그래밍으로 구현하였다.
**온도가 -10도부터 40도까지 가능하므로 dp 인덱스를 구현하기 어려워, 10씩 더해줘 0~50까지로 생각하였다.**
문제의 주된 조건은 사람이 들어올 땐 특정 구간의 온도를 만족해야 하고, 사람이 들어오지 않을 땐 전체 온도 중 아무 온도나 상관이 없다.
이때 사용한 전력의 최솟값을 구해야 한다. (그리디로 접근했지만 최솟값을 구해야 하기 때문에 그리디로 구현할 수 없었다. )
따라서 다이나믹 프로그래밍을 이용해 dp[초][온도] = 특정 초에서 특정 온도일 때 최솟값을 구하도록 구현하였다. 
이때, 배열은 자동으로 0으로 초기화 되는데 -> 이를 모두 MAX_VALUE로 채워주는 것이 중요하다.
처음 모든 전력은 최솟값을 알 수 없기 때문에 최대 값으로 넣어주고, **0초에서의 시작 온도 값만 전력이 0이어야 한다.**
`dp[0][temperature + 10] = 0;`
이후 특정 초에서 특정 온도일 때의 최솟값은 
- 에어컨을 킨 경우
- 에어컨을 끈 경우
로 나누어서 구현하였다. (조건이 많아서 분할하지 않으면 구현이 어려움) 
추가적으로, 사람이 들어올 땐 특정 구간의 온도/사람이 들어오진 않을 땐 전체 온도 중 상관이 없기 때문에
dp[초][온도] 에 해당하는 기준을 다르게 적용하였다. 
```
for(int i=1;i<onboard.length;i++){
if(onboard[i] == 1){
calc(temperature, i, …
```

[programmers_214289] 에어컨

---

4week/Yoojkim/20240122/programmers_258705.java

- dp
2n+1개의 삼각형마다 접근해서 dp로 현재 삼각형 구간에 삼각형으로 채울지 or **마름모로 채울지 경우의 수를 지정한다.**
맨 첫번째 삼각형 구간의 경우 기본 값을 입력한다. (첫번째 구간은 마름모를 채울 수 없음)
이후 
- 삼각형: 이전 구간까지의 삼각형 + 마름모 경우의 수 합
- 마름모 : 이전 구간까지의 삼각형 경우의 수 (그래야만 마름모를 만들 수 있기 때문)
경우의 수를 고려해여 더해준다.
🚨만약 현재 구간의 위쪽에 탑이 존재한다면, 현재 구간의 마름모 값에 현재 구간의 삼각형 경우의 수를 더해준다.
사유: 구간 위쪽에 탑이 존재한다면 이또한 마름모를 구성할 수 있고, 이때의 경우의 수는 삼각형을 배정하는 경우의 수와 동일하기 때문이다. 
```
for(int i=2;i<=section;i++){
dp[i][0] = (dp[i-1][0]+dp[i-1][1])%10007;
dp[i][1] = dp[i-1][0];
if(i%2==0 && tops[i/2-1]==1){
dp[i][1] += dp[i][0];
}
}
```
10007을 나눠주는 것또한 중요했다. 계산을 하면서 중간중간 10007을 나눠야만 통과가 가능하다.
**마지막 결과에서만 나누면 값이 벗어나는 케이스가 존재한다.**
https://school.programmers.co.kr/learn/courses/30/lessons/258705

Yoojkim: programmers_258705.java

---

2week/Yoojkim/20240114/boj_5557.java

- 다이나믹 프로그래밍
이 문제의 중요 포인트는 dp를 위해 2차원 배열을 구현해야 한다는 것이다.
입력 수가 너무 커 DFS로는 풀이할 수 없다. 시간복잡도 O(2^n)
결과 값이 0~20 사이의 값이기 때문에 크기가 21인 배열을 각 수에 할당하여 bottom-up 방식으로 완성할 수 있는 경우의 수를 카운트하고,
마지막 수에 대해서 결과 값에 해당하는 경우의 수(해당 배열 값)을 반환하면 된다.
https://www.acmicpc.net/problem/5557

Yoojkim: boj_5557.java

---

2week/Yoojkim/20240109/programmers_155651.java

- 자료구조 (우선순위 큐)
- 정렬 (Comparable interfac) 
우선순위 큐를 사용하여 시작 시간이 이른 순서대로 예약 방 등록 (예약 방은 종료 시간 이른 순서대로 정렬함)
1. 현재 사용 가능한 방이 있으면 (방의 종료 시간과 예약 시작 시간의 차이가 10분 이상이면) -> 기존 방을 큐에서 빼고 새로운 종료 시간으로 입력 
2. 현재 사용 가능한 방이 없으면 -> 큐에 새로운 종료 시간을 추가함
다른 효과적인 방법이 있는지는 모르겠음. -> 현재는 정렬/그리디 알고리즘을 이용한 풀이라고 보여짐.
https://school.programmers.co.kr/learn/courses/30/lessons/155651

Yoojkim: programmers_155651.java

---

1week/Yoojkim/20240107/boj_9084.java

다이나믹 프로그래밍을 통한 문제 해결
*양식에 맞춰 수정 예정

Yoojkim: boj_9084.java

---

2week/Yoojkim/20240111/programmers_60058.java

자료구조(스택)
문제에 나와있는 대로 필요한 함수를 각각 구현하고 호출하는 방식으로 구현함.
문제 요구사항이 긴 글로 되어있어 코드 작성시, 요구조건을 상세히 따지는 것이 중요함.
https://school.programmers.co.kr/learn/courses/30/lessons/60058

Yoojkim: programmers_60058.java

---

3week/Yoojkim/20240115/programmers_150366.java

- 자료구조 (큐, 리스트)
- 약간의 BFS 
표의 크기가 50x50으로 제한되어 있기 때문에, 250개의 셀 배열을 만들었다.
이때, 셀은 pojo로 같이 병합된 다른 셀의 위치를 큐로 갖게 된다. 
a셀 - b셀 병합 시, a셀의 큐에 b 추가 / b셀의 큐에 a 추가를 통해 병합할 수 있다.
병합 시에 값도 통일되는데, 값은 관계를 통해 나타내는 게 아닌 BFS와 비슷한 방식을 통해 연관된 셀을 모두 방문하며 값을 변경한다. (위와 같이 구현한 이유는 이게 더 간단하고 명확해 보이기 때문이다.)
반환형이 String 배열인데, 이와 관련해서 toArray()를 사용하면 반환할 수 없다.
```
String[] resultArr = new String[results.size()];
resultArr = (String[]) results.toArray(resultArr);
```
위와 같은 식으로 변경해야 반환할 수 있음. 
시간이 너무 많이 걸렸음
1. 문제 자체가 길기도 했지만 체감 한 문제를 두시간 이상 풀었음 -> 특히 트러블 슈팅에서 오랜 시간 소요됨 
2. 코드 길이가 너무 길음 (코딩테스트 용으로 푼 문제가 아닌 느낌...)
https://school.programmers.co.kr/learn/courses/30/lessons/150366

Yoojkim: programmers_150366.java

---

3week/Yoojkim/20240116/programmers_142085.java

- 우선순위 큐
- 정렬
내림차순 comparator를 가지는 우선순위 큐를 생성하여 순서대로 큐에 넣어주며, 넣어줄 때마다 전체 값이 n(가지고 있는 병사 수)를 넘는지 체크함 -> 넘는다면 우선순위 큐에서 가장 큰 값을 poll하여 **큐를 항상 최적화된 상태로 유지함(만족하는 상태)**
큐가 항상 올바른 상태를 유지하기 때문에, 중첩 반복문을 사용할 필요가 없음.
🤔 만약 4가 들어올 때까진 만족하다가 5가 들어왔을 때 전체 병사수를 넘어 무적권을 써야 하는 상황이라면?
4까지는 만족했기 때문에 5가 들어온 경우가 poll되고 큐는 항상 만족 상태를 유지하게 됨. 따라서 반복문을 사용하지 않아도 된다. (만족할 때까지 반복하며 무적권을 쓰지 않아도 됨.)
https://school.programmers.co.kr/learn/courses/30/lessons/142085

Yoojkim: programmers_142085.java

---

3week/Yoojkim/20240117/programmers_258707.java

- 단순 구현
- 탐욕
생각보다 매우 간단한 문제였다.
알아야 할 조건으로는,
1. 라운드가 시작되기 전 카드를 뽑는 건 동전을 쓰지 않아도 된다.
2. 현재 카드를 뽑을지 말지는 커플 카드가 **라운드 시작전 뽑힌 카드인지/아직 뽑히지 않은 카드인지/뽑혔지만 동전을 사용하지 않고 넘어간 카드인지**를 판별하면 된다.
2번 판별법은 간단하게 enum 클래스를 이용하여 구분하였다.
그리디하게 접근한다면 해결할 수 있는 문제였다.
현재 카드를 뽑을지 말지의 우선순위는 커플 카드의 type에 달려있다.
1. 라운드 시작 전 뽑힌 카드인지
2. 뽑혔지만 동전을 사용하지 않고 넘어간 카드인지
3. 뽑히지 않은 카드인지
여부를 알고 처리하면 된다.
https://school.programmers.co.kr/learn/courses/30/lessons/258707

Yoojkim: programmers_258707.java

---

5week/Yoojkim/20240129/boj_1043.java

- BFS
- Greedy
2차원 배열을 이용하여 현재 진실을 알고 있는 사람들을 모두 큐에 넣고, 
이와 관련된 사람들을 모두 큐에 넣어 진실을 아는지 체크한다.
이후, 파티를 돌며 한 명이라도 진실을 안다면 -> 진실을 말하고 다음 파티로 넘어가고
아무도 진실을 모른다면 -> 거짓을 말하도록 한다. 
간단한 문제라서 빠르게 구현하는 것이 중요할 것 같다.
https://www.acmicpc.net/problem/1043

[boj_1043] 거짓말

---

5week/Lydia/20240203/programmers_등대.java

- 트리
- DFS
- 하나의 노드를 기준으로 트리 형태로 만들어 리프노드를 찾음
- 리프노드를 child로 가진 parent는 무조건 등대를 켜야함
- 본인 node를 기준으로 child 등대가 켜져있는지 여부를 체크하여 본인의 등대를 on/off함
- 트리 관련 문제에 많이 약해서 앞으로도 연습이 필요 📌
- [프로그래머스 등대](https://school.programmers.co.kr/learn/courses/30/lessons/133500)

code : Lydia_20240203

---

6week/Lydia/20240210/programmers_요격시스템.java

- 정렬
- 구현
- 미사일 시작점을 기준으로 오름차순 정렬
- 미사일을 요격하는 부분을 갱신해줄 경우, 미사일의 시작점과 초기 설정해둔 미사일의 끝점을 비교하여 요격 지점을 설정
- 만약, 미사일의 시작점은 뒤에 있지만 끝점이 더 앞에 있는 미사일이라면 끝점(targetEnd)를 더 빠른 애로 갱신해줘야함
- [프로그래머스 요격시스템](https://school.programmers.co.kr/learn/courses/30/lessons/181188)

[programmers_181188] 요격 시스템

---

feburary/5week/Yoojkim/programmers_42884.java

Greedy
정렬
자료구조(Stack)
그리디를 이용하여 풀 수 있는 문제였다. 
현재 구간에 한 번은 단속카메라가 존재하여야 하고 **특히, 단속카메라가 겹치는 경우를 알아내는 것이 중요하다.** 
1. 먼저 시작지점을 기준으로 모든 구간을 정렬한다.
2. 스택을 구현하여 그리디하게 구간을 설정한다. 스택 내 값은 CCTV가 존재하는 구간의 값이다.
- 만약 스택이 비었다면 현재 구간을 넣어준다.
- 스택에서 peek한 구간의 끝점이 시작점보다 작다면 구간이 겹치지 않으므로 현재 구간을 push한다.
- 스택에서 peek한 구간의 끝점이 시작점보다 크거나 같다면 **구간이 겹쳐진다.** 
이때, 구간이 겹쳐지기 때문에 겹치는 구간을 계산하여 스택에 넣어줘야 한다. 
겹치는 구간의 시작점은 현재 구간의 시작점이다. (peek한 구간의 끝점이 현재 시작점보다 크거나 같기 때문이다.)
겹치는 구간의 끝점은 peek한 구간의 끝점/현재 구간의 끝점 중 더 작은 값이 된다. 
3. 마지막으로 스택의 size를 리턴한다.
간단한 문제라서 깊게 생각하면 오히려 잘 안 풀릴 듯 ... 
https://school.programmers.co.kr/learn/courses/30/lessons/42884

[programmers_42884] 단속카메라

---

february/5week/Lydia/programmers_네트워크.java

- BFS
- 연결된 네트워크를 기준으로 양방향 그래프를 생성 (이차원 ArrayList)
- n번까지 반복문을 돌면서 이전에 방문하지 않은 경우만 bfs를 호출해줌 
- 이전에 방문하지 않았다는 것은 네트워크가 끊김을 의미 (= answer +1)
- 단순 BFS 문제, 12분 정도 소요된 듯
- [프로그래머스 네트워크](https://school.programmers.co.kr/learn/courses/30/lessons/43162)

[programmers_43162] 네트워크

---

february/5week/Lydia/baekjoon_13164.java

- 탐욕법 (Greedy)
- 하나의 그룹이라고 생각하고 **최대 비용**의 경우를 제외하면서 그룹을 쪼개는 방식으로 구현
- X1, X2, X3, ..... , Xn이 있을 경우, a라는 숫자를 기준으로 X1,...,Xa & Xa+1,...,Xn으로 쪼개게 된다면,
- 처음 : Xn - X1
- 쪼갠 경우: (Xn - Xa+1) + (Xa - X1)
- 결과적으로 처음과 쪼개졌을 경우 Xa - Xa+1의 비용 차이가 남
- 시간복잡도 O(n) 
- 초반에 최소의 비용이 되는 걸 기준으로 그룹핑을 하려했을때는 시간복잡도가 O(n*2) 이 나와 시간초과 발생
- [백준 행복 유치원](https://www.acmicpc.net/problem/13164)

[baekjoon_13164] 행복 유치원
